CREATE TABLE if not exists stg.events stg.events (
	id serial8 primary key,
	event_id UUID,
	event_timestamp TIMESTAMP,
        event_type VARCHAR(16),
	page_url VARCHAR(256),
	page_url_path VARCHAR(256),
	referer_url VARCHAR(32),
	referer_url_scheme VARCHAR(8),
	referer_url_port VARCHAR(5), 
	referer_medium VARCHAR(8),
	utm_medium VARCHAR(16),
	utm_source VARCHAR(16),
	utm_campaign VARCHAR(16),
 	click_id UUID,
  	geo_latitude FLOAT, 
  	geo_longitude FLOAT,
  	geo_country VARCHAR(2), 
  	geo_timezone VARCHAR(32),
  	geo_region_name VARCHAR(32),
  	ip_address VARCHAR(16),
  	browser_name VARCHAR(32),
  	browser_user_agent varchar(512),
  	browser_language varchar(8),
  	os varchar(64),
  	os_name varchar(16),
  	os_timezone varchar(32),
  	device_type varchar(16),
  	device_is_mobile boolean,
  	user_custom_id varchar(64),
  	user_domain_id UUID
);